export const USERS = [
  {
    id: "1",
    name: "John Doe",
    username: "johndoe",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John",
    bio: "Software Developer | Coffee Lover",
    followers: ["2", "3", "4"],
    following: ["2", "5"],
  },
  {
    id: "2",
    name: "Jane Smith",
    username: "janesmith",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
    bio: "Digital Artist | Travel Enthusiast",
    followers: ["1", "3"],
    following: ["1", "3", "4"],
  },
  {
    id: "3",
    name: "Mike Johnson",
    username: "mikej",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mike",
    bio: "Photographer | Nature Lover",
    followers: ["1", "2", "5"],
    following: ["1", "4"],
  },
  {
    id: "4",
    name: "Sarah Wilson",
    username: "sarahw",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    bio: "UX Designer | Book Worm",
    followers: ["2", "5"],
    following: ["1", "2", "3"],
  },
  {
    id: "5",
    name: "David Brown",
    username: "davidb",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=David",
    bio: "Entrepreneur | Tech Enthusiast",
    followers: ["1", "3"],
    following: ["2", "4"],
  },
];
